#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2011 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= soc.o 
obj-y	+= timer.o 
obj-y	+= watchdog.o 
obj-y	+= clock.o 
obj-y	+= ddr.o 
obj-y	+= lowlevel_init.o

