
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xllfifo.h"

/*
* The configuration table for devices
*/

XLlFifo_Config XLlFifo_ConfigTable[] =
{
	{
		XPAR_AXI_SRIO_INITIATOR_FIFO_DEVICE_ID,
		XPAR_AXI_SRIO_INITIATOR_FIFO_BASEADDR,
		XPAR_AXI_SRIO_INITIATOR_FIFO_AXI4_BASEADDR,
		XPAR_AXI_SRIO_INITIATOR_FIFO_DATA_INTERFACE_TYPE
	},
	{
		XPAR_AXI_SRIO_TARGET_FIFO_DEVICE_ID,
		XPAR_AXI_SRIO_TARGET_FIFO_BASEADDR,
		XPAR_AXI_SRIO_TARGET_FIFO_AXI4_BASEADDR,
		XPAR_AXI_SRIO_TARGET_FIFO_DATA_INTERFACE_TYPE
	},
	{
		XPAR_AXI_SRIO_INITIATOR_SHADOWFIFO_DEVICE_ID,
		XPAR_AXI_SRIO_INITIATOR_SHADOWFIFO_BASEADDR,
		XPAR_AXI_SRIO_INITIATOR_SHADOWFIFO_AXI4_BASEADDR,
		XPAR_AXI_SRIO_INITIATOR_SHADOWFIFO_DATA_INTERFACE_TYPE
	}
};


